[theme]
primaryColor = "#ee3800"          # Color de botones y detalles
backgroundColor = "#cffdf2"       # Color del fondo principal
secondaryBackgroundColor = "#76c2bbd7" # Color de la barra lateral (sidebar)
textColor = "#000000"             # Color de la letra
font = "Roboto"               # Estilo de fuente